kind: pipeline
type: docker
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: golang:1.22.2
  commands:
    - echo "Start to Drone CI/CD."
    - go build
    - go test
