kind: pipeline
type: docker
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: golang:1.21.1
  commands:
    - echo "Start to Drone CI/CD."
    - go build
    - go test

trigger:     
  branch: 
  - main
  event:
  - push
